### ISSUE TITLE
Results different with C library

### ISSUE THREAD

**Issue by iboxgithub** [xxtea/xxtea-nodejs#1]
Hi,

I am not sure I am expecting the correct output but I give it a try:
- my C library is always giving me an output on 32 bytes (hex) whereas your JS library will give a result on 12 bytes (base64) so 24 bits (hex)
- I never get the same output between both but I assume may be the same root cause than first point

Here is my code in JS
var k = new Uint32Array([5,0,0,0]); //same behavior with Uint8Array
var Master_Key = new Uint32Array([1, 2, 3, 4]);
var encrypt_k = xxtea_node.encrypt(k, Master_Key); //gives 'VPQjgwjzD7I='

And attached my code in C

[tmp.txt](https://github.com/xxtea/xxtea-nodejs/files/49207/tmp.txt)

Knowing that my target is to work like the target points I let in the code (my arrays with int inside are for comparison purpose)

Could you let me know what I do wrong?

Thanks a lot for your help

**Comment by andot** [comment]
This library is not the original xxtea algorithm.
The parameters of xxtea_node.encrypt is bytes(Uint8Array), not Uint32Array.
The C version( https://github.com/xxtea/xxtea-c ) is also encript bytes(char *), not uint32_t.
