### ISSUE TITLE
xxtea toString 栈溢出：Maximun call stack size exceeded

### ISSUE THREAD

**Issue by rockywu** [xxtea/xxtea-nodejs#2]
使用版本：version 1.1.3
设备：ios 12.2
开发使用xxtea.toString出现 栈溢出：Maximun call stack size exceeded。
排查原因，在ios设备iphone6、iphone6plus、 iphone7、iphone7plus出现
代码片段
当bytes.length = 91853 是出现报错,并且排查可执行的最大length长度：`0xbe92`。
当操作 Unit16Array 长度超过`0xbe92` 则报Maximun call stack size exceeded

```
//调整前：
function toString(bytes) {
    var n = bytes.length;
    if (n === 0) return '';
    return ((n < 0xFFFF) ? toShortString(bytes, n) : toLongString(bytes, n));
}
//调整后：
function toString(bytes) {
    var n = bytes.length;
    if (n === 0) return '';
    return ((n < 0x7FFF) ? toShortString(bytes, n) : toLongString(bytes, n));
}
```

**Comment by andot** [comment]
好的，多谢
