### ISSUE TITLE
xxtea-java

### ISSUE THREAD

**Issue by exetree** [xxtea/xxtea-nodejs#4]
Hello,
I was using “xxtea-java” and now I am moving to “xxtea-node”. I was unable to decrypt the data that was encrypted in java by using the NodeJS version. To solve that in the NodeJS version I have changed “UInt32Array” to “Int32Array” and now it is working.
 I thought that it maybe will be helpful for you. Thank You for your code it is big help for me.

**Comment by andot** [comment]
I use uint32 array in all languages. Even in Java, I use unsigned shift operation.
