### ISSUE TITLE
ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by iamsarav** [xxtea/xxtea-nodejs#7]
https://github.com/xxtea/xxtea-nodejs/blob/fcdd461cb430290f530167f23c9fa50e445ab4b0/lib/xxtea.js#L305

In the Decrypt method new Buffer line is throwing `"ReferenceError: Buffer is not defined"`, but if I replace this line with the following line it works fine "`**require('buffer/').Buffer.from**`". 

Whats the difference between both two and how to fix the first said issue? 

Our Environment : 

Node  : V14.17.3
NPM :  6.14.13

![image](https://user-images.githubusercontent.com/13994836/209524484-c0395ab3-d308-4060-a444-601209f03771.png)

**Comment by andot** [comment]
Thank you. I fixed it on v1.1.5.
